export const RUTAS = [
  {
    id: 'capital-volcan-lago',
    region: 'San Salvador',
    titulo: 'Ruta de la capital: volcán y caldera',
    lema: 'El Boquerón mira la ciudad; Ilopango es el lago que nació de fuego.',
    duracion: 'Un día',
    km: '≈ 35 km',
    puntos: [
      {
        nombre: 'Volcán El Boquerón',
        hora: '08:00',
        nota: 'Cráter fresco, sendero corto. Abrigo ligero y zapatos cómodos.',
        color: '#0b6fb3',
      },
      {
        nombre: 'Lago de Ilopango',
        hora: '13:00',
        nota: 'Caldera con agua para mirar, navegar o almorzar a la orilla.',
        color: '#168a1a',
      },
    ],
  },
  {
    id: 'volcan-al-mar',
    region: 'San Miguel',
    titulo: 'Ruta del Volcán al Mar',
    lema: 'Del parque a la cumbre, y de la cumbre a las olas.',
    duracion: 'Un día completo',
    km: '≈ 55 km',
    puntos: [
      {
        nombre: 'Centro Histórico de San Miguel',
        hora: '08:00',
        nota: 'Catedral y Parque David J. Guzmán. Pupusas La Catedral antes de subir.',
        color: '#0b6fb3',
      },
      {
        nombre: 'Volcán Chaparrastique',
        hora: '10:30',
        nota: 'Ascenso con guía local. Llevar agua y calzado de tracción.',
        color: '#168a1a',
      },
      {
        nombre: 'Playa El Cuco',
        hora: '16:00',
        nota: 'Bajar al mar: minutas, artesanías y atardecer en Chirilagua.',
        color: '#f4a000',
      },
    ],
  },
  {
    id: 'vertientes-oriente',
    region: 'San Miguel',
    titulo: 'Ruta de las Vertientes',
    lema: 'Agua de nacimiento, caldera seca y mesa oriental.',
    duracion: 'Medio día a un día',
    km: '≈ 40 km',
    puntos: [
      {
        nombre: 'Turicentro Flor del Río',
        hora: '09:00',
        nota: 'Piscinas de vertiente en Moncagua. Ideal para niños.',
        color: '#0b6fb3',
      },
      {
        nombre: 'Laguna Seca El Pacayal',
        hora: '12:30',
        nota: 'Caldera del Chinameca con guía. Cafetales y fumarolas.',
        color: '#168a1a',
      },
      {
        nombre: 'Restaurante Mirador Oriental',
        hora: '16:30',
        nota: 'Cerrar con comida típica sobre la Panamericana.',
        color: '#f4a000',
      },
    ],
  },
  {
    id: 'morazan-barro-memoria',
    region: 'Morazán',
    titulo: 'Ruta de Paz: barro, memoria y montaña',
    lema: 'Guatajiagua tiñe el barro de negro; el norte guarda la historia y el agua.',
    duracion: 'Un día completo',
    km: '≈ 80 km',
    puntos: [
      {
        nombre: 'Guatajiagua',
        hora: '08:00',
        nota: 'Talleres de barro negro trabajando temprano. Llevar efectivo para comprar en el taller.',
        color: '#0b6fb3',
      },
      {
        nombre: 'El Mozote',
        hora: '11:00',
        nota: 'Sitio de memoria. Ir con guía de la comunidad y guardar silencio en el monumento.',
        color: '#168a1a',
      },
      {
        nombre: 'Perquín',
        hora: '13:30',
        nota: 'Almuerzo, museo y café de altura. El pueblo se camina en poco tiempo.',
        color: '#f4a000',
      },
      {
        nombre: 'Cascada El Perol',
        hora: '16:00',
        nota: 'Bajada corta con guía para cerrar el día. Calzado con tracción.',
        color: '#0b6fb3',
      },
    ],
  },
  {
    id: 'libertad-costa-memoria',
    region: 'La Libertad',
    titulo: 'Ruta de costa y memoria',
    lema: 'El Tunco es ola; Joya de Cerén es el pueblo que el volcán guardó.',
    duracion: 'Un día',
    km: '≈ 45 km',
    puntos: [
      {
        nombre: 'Joya de Cerén',
        hora: '09:00',
        nota: 'Patrimonio mundial. Ir temprano, antes del calor.',
        color: '#0b6fb3',
      },
      {
        nombre: 'Playa El Tunco',
        hora: '14:00',
        nota: 'Surf, atardecer y pueblo de costa. Efectivo para el consumo local.',
        color: '#f4a000',
      },
    ],
  },
];
