-- =============================================================================
-- GeoTurismoSV — script único para Supabase
-- Proyecto de base de datos: geoturismosv
--
-- CÓMO USARLO
-- 1. Crea un proyecto en https://supabase.com (nombre sugerido: geoturismosv).
-- 2. Authentication → Providers → Email: activa Email.
--    En Authentication → Providers → Email, desactiva
--    "Confirm email" mientras pruebas (si no, el login pide confirmar correo).
-- 3. SQL Editor → New query → pega ESTE archivo completo → Run.
-- 4. Authentication → Users → Add user (marca Auto Confirm User):
--      admin@geoturismosv.com  /  12345678
--      usuario@geoturismosv.com / 12345678
-- 5. Si el UPDATE final no cambió filas (todavía no existían los usuarios),
--    ejecuta supabase/promover-admin.sql.
--
-- Este script es idempotente: puedes volver a ejecutarlo sin romper datos.
-- No toca el repositorio original de Laravel.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- -----------------------------------------------------------------------------
-- 1) Primero la tabla profiles.
--    is_admin() es LANGUAGE sql: Postgres valida public.profiles al CREAR
--    la función. Si la tabla no existe todavía, falla con 42P01.
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = timezone('utc', now());
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  nombre text NOT NULL,
  email text UNIQUE,
  rol text NOT NULL DEFAULT 'usuario' CHECK (rol IN ('admin', 'usuario')),
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1
    FROM public.profiles
    WHERE id = auth.uid()
      AND rol = 'admin'
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.protect_profile_rol()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'UPDATE'
     AND auth.uid() IS NOT NULL
     AND NEW.rol IS DISTINCT FROM OLD.rol THEN
    NEW.rol := OLD.rol;
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, nombre, email, rol)
  VALUES (
    NEW.id,
    COALESCE(
      NEW.raw_user_meta_data->>'nombre',
      NEW.raw_user_meta_data->>'name',
      split_part(NEW.email, '@', 1)
    ),
    NEW.email,
    'usuario'
  )
  ON CONFLICT (id) DO UPDATE
    SET email = EXCLUDED.email,
        nombre = COALESCE(public.profiles.nombre, EXCLUDED.nombre);

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS profiles_set_updated_at ON public.profiles;
CREATE TRIGGER profiles_set_updated_at
BEFORE UPDATE ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS profiles_protect_rol ON public.profiles;
CREATE TRIGGER profiles_protect_rol
BEFORE UPDATE ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.protect_profile_rol();

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- -----------------------------------------------------------------------------
-- Tabla: categorias
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.categorias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre varchar(100) NOT NULL UNIQUE,
  nombre_en varchar(255),
  descripcion text NOT NULL,
  descripcion_en text,
  estado boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

DROP TRIGGER IF EXISTS categorias_set_updated_at ON public.categorias;
CREATE TRIGGER categorias_set_updated_at
BEFORE UPDATE ON public.categorias
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- -----------------------------------------------------------------------------
-- Tabla: destinos
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.destinos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria_id bigint NOT NULL REFERENCES public.categorias (id) ON DELETE CASCADE,
  nombre varchar(150) NOT NULL UNIQUE,
  nombre_en varchar(255),
  descripcion text NOT NULL,
  descripcion_en text,
  ubicacion varchar(150) NOT NULL,
  ubicacion_en varchar(255),
  departamento varchar(100),
  municipio varchar(100),
  latitud numeric(10, 7),
  longitud numeric(10, 7),
  direccion varchar(255),
  direccion_en varchar(255),
  contacto varchar(255),
  contacto_en varchar(255),
  telefono varchar(255),
  sitio_web varchar(255),
  imagen varchar(500),
  costo_estimado numeric(8, 2) NOT NULL DEFAULT 0,
  dias_atencion text,
  dias_atencion_en varchar(255),
  hora_apertura time,
  hora_cierre time,
  horario varchar(150),
  horario_en varchar(255),
  recomendaciones text,
  recomendaciones_en text,
  estado boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS destinos_categoria_id_idx ON public.destinos (categoria_id);
CREATE INDEX IF NOT EXISTS destinos_departamento_idx ON public.destinos (departamento);
CREATE INDEX IF NOT EXISTS destinos_estado_idx ON public.destinos (estado);

DROP TRIGGER IF EXISTS destinos_set_updated_at ON public.destinos;
CREATE TRIGGER destinos_set_updated_at
BEFORE UPDATE ON public.destinos
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- -----------------------------------------------------------------------------
-- Tabla: favoritos
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.favoritos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  destino_id bigint NOT NULL REFERENCES public.destinos (id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  UNIQUE (user_id, destino_id)
);

CREATE INDEX IF NOT EXISTS favoritos_user_id_idx ON public.favoritos (user_id);

DROP TRIGGER IF EXISTS favoritos_set_updated_at ON public.favoritos;
CREATE TRIGGER favoritos_set_updated_at
BEFORE UPDATE ON public.favoritos
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE OR REPLACE FUNCTION public.delete_own_account()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  uid uuid := auth.uid();
BEGIN
  IF uid IS NULL THEN
    RAISE EXCEPTION 'No autenticado';
  END IF;

  DELETE FROM auth.users WHERE id = uid;
END;
$$;

GRANT EXECUTE ON FUNCTION public.delete_own_account() TO authenticated;

-- -----------------------------------------------------------------------------
-- Row Level Security
-- -----------------------------------------------------------------------------

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.destinos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.favoritos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_select_own_or_admin" ON public.profiles;
CREATE POLICY "profiles_select_own_or_admin"
ON public.profiles FOR SELECT
USING (auth.uid() = id OR public.is_admin());

DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own"
ON public.profiles FOR UPDATE
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "categorias_public_read" ON public.categorias;
CREATE POLICY "categorias_public_read"
ON public.categorias FOR SELECT
USING (estado = true OR public.is_admin());

DROP POLICY IF EXISTS "categorias_admin_insert" ON public.categorias;
CREATE POLICY "categorias_admin_insert"
ON public.categorias FOR INSERT
TO authenticated
WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "categorias_admin_update" ON public.categorias;
CREATE POLICY "categorias_admin_update"
ON public.categorias FOR UPDATE
TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "categorias_admin_delete" ON public.categorias;
CREATE POLICY "categorias_admin_delete"
ON public.categorias FOR DELETE
TO authenticated
USING (public.is_admin());

DROP POLICY IF EXISTS "destinos_public_read" ON public.destinos;
CREATE POLICY "destinos_public_read"
ON public.destinos FOR SELECT
USING (estado = true OR public.is_admin());

DROP POLICY IF EXISTS "destinos_admin_insert" ON public.destinos;
CREATE POLICY "destinos_admin_insert"
ON public.destinos FOR INSERT
TO authenticated
WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "destinos_admin_update" ON public.destinos;
CREATE POLICY "destinos_admin_update"
ON public.destinos FOR UPDATE
TO authenticated
USING (public.is_admin())
WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "destinos_admin_delete" ON public.destinos;
CREATE POLICY "destinos_admin_delete"
ON public.destinos FOR DELETE
TO authenticated
USING (public.is_admin());

DROP POLICY IF EXISTS "favoritos_select_own" ON public.favoritos;
CREATE POLICY "favoritos_select_own"
ON public.favoritos FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "favoritos_insert_own" ON public.favoritos;
CREATE POLICY "favoritos_insert_own"
ON public.favoritos FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "favoritos_delete_own" ON public.favoritos;
CREATE POLICY "favoritos_delete_own"
ON public.favoritos FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- -----------------------------------------------------------------------------
-- Storage: bucket de fotos subidas por el admin
-- Las imágenes de semilla viven en /public del frontend (GitHub Pages).
-- Las nuevas fotos del CRUD van a este bucket.
-- -----------------------------------------------------------------------------

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'destinos',
  'destinos',
  true,
  2293760,
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/jpg']
)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "destinos_images_public_read" ON storage.objects;
CREATE POLICY "destinos_images_public_read"
ON storage.objects FOR SELECT
USING (bucket_id = 'destinos');

DROP POLICY IF EXISTS "destinos_images_admin_insert" ON storage.objects;
CREATE POLICY "destinos_images_admin_insert"
ON storage.objects FOR INSERT
TO authenticated
WITH CHECK (bucket_id = 'destinos' AND public.is_admin());

DROP POLICY IF EXISTS "destinos_images_admin_update" ON storage.objects;
CREATE POLICY "destinos_images_admin_update"
ON storage.objects FOR UPDATE
TO authenticated
USING (bucket_id = 'destinos' AND public.is_admin())
WITH CHECK (bucket_id = 'destinos' AND public.is_admin());

DROP POLICY IF EXISTS "destinos_images_admin_delete" ON storage.objects;
CREATE POLICY "destinos_images_admin_delete"
ON storage.objects FOR DELETE
TO authenticated
USING (bucket_id = 'destinos' AND public.is_admin());

-- -----------------------------------------------------------------------------
-- Semilla: categorías (ids 1–6, iguales al proyecto original)
-- -----------------------------------------------------------------------------

INSERT INTO public.categorias (id, nombre, nombre_en, descripcion, descripcion_en, estado)
VALUES
  (1, 'Playas', 'Beaches',
   'Destinos costeros ideales para descanso, recreación y turismo familiar.',
   'Coastal destinations ideal for relaxation, recreation, and family tourism.',
   true),
  (2, 'Montañas y naturaleza', 'Mountains and nature',
   'Lugares naturales, volcanes, miradores y espacios para aventura.',
   'Natural places, volcanoes, viewpoints, and spaces for adventure.',
   true),
  (3, 'Restaurantes', 'Restaurants',
   'Establecimientos gastronómicos recomendados para visitantes nacionales y extranjeros.',
   'Recommended gastronomic establishments for national and foreign visitors.',
   true),
  (4, 'Hoteles', 'Hotels',
   'Opciones de alojamiento para turistas dentro de El Salvador.',
   'Accommodation options for tourists within El Salvador.',
   true),
  (5, 'Centros recreativos', 'Recreation centers',
   'Espacios familiares y recreativos para visitar en diferentes zonas del país.',
   'Family and recreational spaces to visit in different areas of the country.',
   true),
  (6, 'Sitios culturales', 'Cultural sites',
   'Lugares históricos, arqueológicos y culturales de interés turístico.',
   'Historical, archaeological, and cultural places of tourist interest.',
   true)
ON CONFLICT (nombre) DO UPDATE
SET
  nombre_en = EXCLUDED.nombre_en,
  descripcion = EXCLUDED.descripcion,
  descripcion_en = EXCLUDED.descripcion_en,
  estado = EXCLUDED.estado;

SELECT setval(pg_get_serial_sequence('public.categorias', 'id'), GREATEST((SELECT MAX(id) FROM public.categorias), 6));

-- -----------------------------------------------------------------------------
-- Semilla: destinos (16 lugares del DestinoSeeder original)
-- imagen = ruta relativa en /public del frontend
-- -----------------------------------------------------------------------------

INSERT INTO public.destinos (
  nombre, nombre_en, categoria_id,
  descripcion, descripcion_en,
  ubicacion, ubicacion_en, departamento, municipio,
  direccion, direccion_en, contacto, contacto_en, telefono, sitio_web, imagen,
  costo_estimado, dias_atencion, dias_atencion_en, hora_apertura, hora_cierre,
  horario, horario_en, recomendaciones, recomendaciones_en, estado, latitud, longitud
)
VALUES
(
  'Playa El Tunco', 'El Tunco Beach', 1,
  $d$Uno de los destinos de playa más populares de El Salvador, conocido por su ambiente juvenil, surf, atardeceres y vida nocturna.$d$,
  $d$One of the most popular beach destinations in El Salvador, known for its youthful atmosphere, surfing, sunsets, and nightlife.$d$,
  'Tamanique, La Libertad', 'Tamanique, La Libertad', 'La Libertad', 'Tamanique',
  'Zona costera del departamento de La Libertad', 'Coastal area of La Libertad department',
  'Información turística local', 'Local tourist information', '2600-0101', NULL,
  'img/destinos/tunco.jpg',
  15.00, 'Sábado y domingo', 'Saturday and Sunday', '12:48', '05:50',
  'Abierto todos los días', 'Open every day',
  $d$Llevar ropa cómoda, protector solar y efectivo para consumo local.$d$,
  $d$Bring comfortable clothes, sunscreen, and cash for local consumption.$d$,
  true, 13.4942000, -89.3812000
),
(
  'Volcán El Boquerón', 'El Boquerón Volcano', 2,
  $d$Parque natural ubicado en San Salvador, famoso por su cráter, clima fresco y senderos accesibles para visitantes.$d$,
  $d$Natural park located in San Salvador, famous for its crater, cool climate, and accessible trails for visitors.$d$,
  'San Salvador', 'San Salvador', 'San Salvador', 'San Salvador',
  'Parque Nacional El Boquerón', 'El Boquerón National Park',
  'Administración del parque', 'Park administration', '2600-0102', NULL,
  'img/destinos/boqueron.jpg',
  5.00, 'Todos los días', 'Every day', '08:00', '17:00',
  '8:00 a.m. - 5:00 p.m.', '8:00 a.m. - 5:00 p.m.',
  $d$Usar zapatos cómodos y llevar abrigo ligero por el clima fresco.$d$,
  $d$Wear comfortable shoes and bring a light jacket due to the cool weather.$d$,
  true, 13.7340000, -89.2870000
),
(
  'Suchitoto', 'Suchitoto', 6,
  $d$Pueblo turístico reconocido por sus calles empedradas, arquitectura colonial, arte, cultura y vista al lago Suchitlán.$d$,
  $d$Tourist town renowned for its cobblestone streets, colonial architecture, art, culture, and views of Lake Suchitlán.$d$,
  'Cuscatlán', 'Cuscatlán', 'Cuscatlán', 'Suchitoto',
  'Centro histórico de Suchitoto', 'Historic center of Suchitoto',
  'Información turística municipal', 'Municipal tourist information', '2600-0103', NULL,
  'img/destinos/suchitoto.jpg',
  20.00, 'Todos los días', 'Every day', NULL, NULL,
  'Abierto todos los días', 'Open every day',
  $d$Ideal para caminar, tomar fotografías y degustar comida típica.$d$,
  $d$Ideal for walking, taking photos, and tasting local food.$d$,
  true, 13.9381000, -89.0278000
),
(
  'Joya de Cerén', 'Joya de Cerén', 6,
  $d$Sitio arqueológico declarado Patrimonio de la Humanidad, conocido como la Pompeya de América.$d$,
  $d$Archaeological site declared a World Heritage Site, known as the Pompeii of America.$d$,
  'La Libertad', 'La Libertad', 'La Libertad', 'San Juan Opico',
  'San Juan Opico, La Libertad', 'San Juan Opico, La Libertad',
  'Administración del sitio arqueológico', 'Archaeological site administration', '2600-0104', NULL,
  'img/destinos/joya-de-ceren.jpg',
  3.00, 'Todos los días', 'Every day', '07:00', '16:53',
  '9:00 a.m. - 4:00 p.m.', '9:00 a.m. - 4:00 p.m.',
  $d$Consultar horarios actualizados antes de visitar.$d$,
  $d$Check updated hours before visiting.$d$,
  true, 13.8277000, -89.3603000
),
(
  'Lago de Coatepeque', 'Lake Coatepeque', 2,
  $d$Lago de origen volcánico reconocido por sus aguas azuladas, restaurantes, miradores y actividades acuáticas.$d$,
  $d$Lake of volcanic origin known for its blue waters, restaurants, viewpoints, and water activities.$d$,
  'Santa Ana', 'Santa Ana', 'Santa Ana', 'El Congo / Coatepeque',
  'Municipios de El Congo y Coatepeque', 'Municipalities of El Congo and Coatepeque',
  'Información turística local', 'Local tourist information', '2600-0105', NULL,
  'img/destinos/coatepeque.jpg',
  25.85, 'Todos los días', 'Every day', NULL, NULL,
  'Abierto todos los días', 'Open every day',
  $d$Reservar con anticipación si se visitan restaurantes o alojamientos.$d$,
  $d$Book in advance if visiting restaurants or accommodations.$d$,
  true, 13.8643000, -89.5450000
),
(
  'Playa El Cuco', 'El Cuco Beach', 1,
  $d$Playa reconocida de la zona oriental de El Salvador, ideal para descanso, turismo familiar y gastronomía local.$d$,
  $d$Renowned beach in the eastern part of El Salvador, ideal for rest, family tourism, and local cuisine.$d$,
  'Chirilagua, San Miguel', 'Chirilagua, San Miguel', 'San Miguel', 'Chirilagua',
  'Zona costera de Playa El Cuco, Chirilagua, San Miguel.', 'Coastal area of El Cuco Beach, Chirilagua, San Miguel.',
  'Información turística local', 'Local tourist information', '2600-0001', NULL,
  'images/elcuco_real.png',
  15.00, 'Todos los días', 'Every day', '07:00', '18:00',
  NULL, NULL,
  $d$Llevar protector solar, ropa cómoda y visitar durante la mañana.$d$,
  $d$Bring sunscreen, comfortable clothes, and visit during the morning.$d$,
  true, 13.1739000, -88.1078000
),
(
  'Volcán Chaparrastique', 'Chaparrastique Volcano', 2,
  $d$Uno de los volcanes más representativos de la zona oriental, atractivo para visitantes interesados en naturaleza y paisajes.$d$,
  $d$One of the most representative volcanoes in the eastern zone, attractive to visitors interested in nature and landscapes.$d$,
  'San Miguel', 'San Miguel', 'San Miguel', 'San Miguel',
  'Área del Volcán Chaparrastique, San Miguel.', 'Chaparrastique Volcano area, San Miguel.',
  'Información turística municipal', 'Municipal tourist information', '2600-0002', NULL,
  'images/chaparrastique_real.png',
  10.00, 'Todos los días', 'Every day', '06:00', '16:00',
  NULL, NULL,
  $d$Usar calzado adecuado, llevar agua y verificar condiciones climáticas antes de visitar.$d$,
  $d$Wear appropriate footwear, bring water, and check weather conditions before visiting.$d$,
  true, 13.4347000, -88.2697000
),
(
  'Laguna de Alegría', 'Alegría Lagoon', 2,
  $d$Destino natural ubicado en Usulután, conocido por sus paisajes, clima agradable y valor turístico.$d$,
  $d$Natural destination located in Usulután, known for its landscapes, pleasant climate, and tourist value.$d$,
  'Alegría, Usulután', 'Alegría, Usulután', 'Usulután', 'Alegría',
  'Laguna de Alegría, municipio de Alegría, Usulután.', 'Alegría Lagoon, municipality of Alegría, Usulután.',
  'Información turística de Alegría', 'Alegría tourist information', '2600-0003', NULL,
  'images/alegria_real.png',
  8.00, 'Todos los días', 'Every day', '07:00', '17:00',
  NULL, NULL,
  $d$Ideal para fotografía, caminatas y turismo familiar.$d$,
  $d$Ideal for photography, hiking, and family tourism.$d$,
  true, 13.5069000, -88.4856000
),
(
  'Golfo de Fonseca', 'Gulf of Fonseca', 1,
  $d$Zona costera compartida por El Salvador, Honduras y Nicaragua, reconocida por sus paisajes marítimos e islas.$d$,
  $d$Coastal area shared by El Salvador, Honduras, and Nicaragua, known for its maritime landscapes and islands.$d$,
  'La Unión', 'La Unión', 'La Unión', 'La Unión',
  'Zona costera del Golfo de Fonseca, La Unión.', 'Coastal area of the Gulf of Fonseca, La Unión.',
  'Información turística local', 'Local tourist information', '2600-0004', NULL,
  'images/golfo_real.png',
  20.00, 'Todos los días', 'Every day', '07:00', '17:00',
  NULL, NULL,
  $d$Consultar disponibilidad de recorridos en lancha y llevar protección solar.$d$,
  $d$Check availability of boat tours and bring sun protection.$d$,
  true, 13.3369000, -87.8439000
),
(
  'Laguna Seca El Pacayal', 'Dry Lagoon El Pacayal', 5,
  $d$La Laguna Seca El Pacayal es un imponente destino geográfico en la cima del Volcán Chinameca, a 1,350 metros de altura. A pesar de su nombre, es una enorme caldera volcánica seca originada hace 59,000 años por una de las erupciones más potentes de Centroamérica. Hoy en día, su cráter está cubierto por cafetales y un clima fresco, ofreciendo un paisaje donde incluso se pueden observar fumarolas geotérmicas.$d$,
  $d$Dry Lagoon El Pacayal is an imposing geographical destination at the top of the Chinameca Volcano, at an altitude of 1,350 meters. Despite its name, it is a massive dry volcanic caldera originating 59,000 years ago from one of the most powerful eruptions in Central America. Today, its crater is covered by coffee plantations and a cool climate, offering a landscape where geothermal fumaroles can even be observed.$d$,
  'Chinameca, San Miguel', 'Chinameca, San Miguel', 'San Miguel', 'Chinameca',
  'Laguna Seca El Pacayal, Chinameca, San Miguel', 'Dry Lagoon El Pacayal, Chinameca, San Miguel',
  'Administración del centro recreativo', 'Recreation center administration', '2600-0005', NULL,
  'images/pacayal_paisaje.png',
  0.00, 'Todos los días', 'Every day', NULL, NULL,
  NULL, NULL,
  $d$Es indispensable el acompañamiento de un guía local. Se recomienda usar calzado con buena tracción, ropa para clima fresco y llevar abundante hidratación.$d$,
  $d$It is essential to be accompanied by a local guide. It is recommended to wear footwear with good traction, clothing for cool weather, and bring plenty of hydration.$d$,
  true, 13.4833000, -88.1833000
),
(
  'Restaurante Mirador Oriental', 'Mirador Oriental Restaurant', 3,
  $d$Restaurante turístico con comida típica salvadoreña y ambiente familiar.$d$,
  $d$Tourist restaurant with typical Salvadoran food and a family atmosphere.$d$,
  'San Miguel', 'San Miguel', 'San Miguel', 'San Miguel',
  'Carretera Panamericana, San Miguel.', 'Pan-American Highway, San Miguel.',
  'Atención al cliente', 'Customer service', '2600-0002', 'https://www.facebook.com/',
  'images/restaurante_mirador_oriental.jpg',
  18.00, 'Martes a domingo', 'Tuesday to Sunday', '10:00', '21:00',
  NULL, NULL,
  $d$Ideal para almuerzos familiares y visitantes que buscan gastronomía local.$d$,
  $d$Ideal for family lunches and visitors looking for local cuisine.$d$,
  true, 13.4830000, -88.1750000
),
(
  'Hotel Vista Azul', 'Vista Azul Hotel', 4,
  $d$Hotel turístico orientado a visitantes que buscan alojamiento cerca de la playa.$d$,
  $d$Tourist hotel aimed at visitors looking for accommodation near the beach.$d$,
  'El Cuco, San Miguel', 'El Cuco, San Miguel', 'San Miguel', 'Chirilagua',
  'Calle principal hacia Playa El Cuco, Chirilagua.', 'Main street toward El Cuco Beach, Chirilagua.',
  'Recepción del hotel', 'Hotel reception', '2600-0003', 'https://www.example.com',
  'images/hotel_vista_azul.jpg',
  45.00, 'Todos los días', 'Every day', '00:00', '23:59',
  NULL, NULL,
  $d$Recomendado para visitantes que desean hospedarse cerca de la playa.$d$,
  $d$Recommended for visitors who want to stay near the beach.$d$,
  true, 13.1760000, -88.1050000
),
(
  'Centro Histórico de Alegría', 'Alegría Historic Center', 6,
  $d$Zona cultural con arquitectura tradicional, gastronomía local y espacios para recorrer en familia.$d$,
  $d$Cultural area with traditional architecture, local gastronomy, and spaces for family tours.$d$,
  'Alegría, Usulután', 'Alegría, Usulután', 'Usulután', 'Alegría',
  'Centro del municipio de Alegría, Usulután.', 'Center of the municipality of Alegría, Usulután.',
  'Casa de la cultura local', 'Local house of culture', '2600-0008', NULL,
  'images/centro_historico_alegria.jpeg',
  5.00, 'Todos los días', 'Every day', '08:00', '18:00',
  NULL, NULL,
  $d$Visitar el parque central, probar comida local y recorrer los alrededores.$d$,
  $d$Visit the central park, try local food, and explore the surroundings.$d$,
  true, 13.5000000, -88.4833000
),
(
  'Hostal y Parque Acuático El Edén de Brizuela', 'El Edén de Brizuela Hostel and Water Park', 5,
  $d$Este es uno de los destinos recreativos más recientes y populares en Nueva Guadalupe, ideal para quienes buscan refrescarse y pasar un día de relajación familiar. El lugar destaca por sus atractivas instalaciones acuáticas, que incluyen opciones para niños, una piscina semi-olímpica y la llamativa "piscina de la isla", cuyo diseño simula un pequeño montículo de tierra en el centro del agua. Además de los baños, el complejo ofrece una experiencia integral con servicio de restaurante especializado en platillos como churrascos, aves y mariscos a la plancha, área de bar, mesas de billar y espacios de descanso. Para quienes desean extender su visita, también cuenta con habitaciones de alojamiento, convirtiéndolo en un pequeño resort muy completo para los turistas.$d$,
  $d$This is one of the most recent and popular recreational destinations in Nueva Guadalupe, ideal for those looking to cool off and spend a day of family relaxation. The place stands out for its attractive water facilities, which include options for children, a semi-olympic pool, and the striking "island pool", whose design simulates a small mound of earth in the center of the water. In addition to the pools, the complex offers a comprehensive experience with a restaurant service specializing in dishes such as churrascos, poultry, and grilled seafood, a bar area, billiard tables, and resting spaces. For those who wish to extend their visit, it also has accommodation rooms, making it a very complete small resort for tourists.$d$,
  'Nueva Guadalupe, San Miguel', 'Nueva Guadalupe, San Miguel', 'San Miguel', 'Nueva Guadalupe',
  'Nueva Guadalupe, San Miguel.', 'Nueva Guadalupe, San Miguel.',
  'Administración del parque', 'Park administration', '2600-0000', NULL,
  'images/eden_brizuela.jpg',
  5.00, 'Todos los días', 'Every day', '09:00', '20:00',
  NULL, NULL,
  $d$Llevar traje de baño y ropa cómoda. Ideal para familias.$d$,
  $d$Bring a swimsuit and comfortable clothes. Ideal for families.$d$,
  true, 13.5317600, -88.3506000
),
(
  'Turicentro Flor del Río', 'Flor del Río Tourist Center', 5,
  $d$Turicentro natural reconocido por sus refrescantes piscinas de agua de vertiente, rodeado de vegetación y espacios ideales para el descanso familiar. Es un destino popular para refrescarse durante el fin de semana.$d$,
  $d$Natural tourist center known for its refreshing spring water pools, surrounded by vegetation and ideal spaces for family rest. It is a popular destination to cool off during the weekend.$d$,
  'Moncagua, San Miguel', 'Moncagua, San Miguel', 'San Miguel', 'Moncagua',
  'Moncagua, San Miguel.', 'Moncagua, San Miguel.',
  'Administración del turicentro', 'Tourist center administration', '2600-0000', NULL,
  'images/flor_del_rio.jpg',
  5.00, 'Todos los días', 'Every day', '08:00', '17:00',
  NULL, NULL,
  $d$Llevar traje de baño, protector solar y ropa cómoda.$d$,
  $d$Bring a swimsuit, sunscreen, and comfortable clothes.$d$,
  true, 13.6065700, -88.2545000
),
(
  'Lago de Ilopango', 'Lake Ilopango', 2,
  $d$El lago de Ilopango es un lago de origen volcánico en El Salvador. Mide 8 x 11 km, tiene una superficie de 72 km² y una profundidad de 230 m. Es el lago natural más grande de El Salvador. Sus aguas son ideales para la pesca y la navegación.$d$,
  $d$Lake Ilopango is a volcanic lake in El Salvador. It measures 8 x 11 km, has a surface area of 72 km² and a depth of 230 m. It is the largest natural lake in El Salvador. Its waters are ideal for fishing and boating.$d$,
  'San Salvador, Cuscatlán y La Paz', 'San Salvador, Cuscatlán and La Paz', 'San Salvador', 'Ilopango',
  'A 16 km de la ciudad de San Salvador', '16 km from the city of San Salvador',
  'Información turística local', 'Local tourist information', '2200-0000', NULL,
  'img/destinos/ilopango.jpg',
  5.00, 'Todos los días', 'Every day', '08:00', '17:00',
  'Abierto de lunes a domingo de 8:00 AM a 5:00 PM', 'Open Monday to Sunday from 8:00 AM to 5:00 PM',
  $d$Llevar protector solar, ropa ligera y cámara fotográfica para los hermosos paisajes de la caldera volcánica.$d$,
  $d$Bring sunscreen, light clothing, and a camera for the beautiful volcanic caldera landscapes.$d$,
  true, 13.6703000, -89.0531000
)
ON CONFLICT (nombre) DO NOTHING;

-- Si los usuarios de Auth se crearon ANTES de este script, no tienen fila en profiles.
INSERT INTO public.profiles (id, nombre, email, rol)
SELECT
  u.id,
  COALESCE(
    u.raw_user_meta_data->>'nombre',
    u.raw_user_meta_data->>'name',
    split_part(u.email, '@', 1)
  ),
  u.email,
  CASE
    WHEN lower(u.email) = 'admin@geoturismosv.com' THEN 'admin'
    ELSE 'usuario'
  END
FROM auth.users u
ON CONFLICT (id) DO UPDATE
  SET email = EXCLUDED.email;

-- =============================================================================
-- PROMOVER ADMIN (por si el INSERT de arriba no alcanzó)
-- =============================================================================

UPDATE public.profiles
SET rol = 'admin',
    nombre = 'Administrador GeoTurismoSV'
WHERE lower(email) = 'admin@geoturismosv.com';

UPDATE public.profiles
SET nombre = 'Usuario Turista'
WHERE lower(email) = 'usuario@geoturismosv.com';
